CREATE TABLE GameDev.WordList(
	RECORD_ID INT PRIMARY KEY IDENTITY,
	LANG_TYPE_ID INT NOT NULL,
	WORD VARCHAR(MAX) NOT NULL,
	DEFINITION VARCHAR(MAX) NULL
)

CREATE TABLE GameDev.LanguageType(
	LANG_TYPE_ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(MAX) NOT NULL
)

ALTER TABLE GameDev.WordList
   ADD CONSTRAINT FK_LangType FOREIGN KEY (LANG_TYPE_ID)
      REFERENCES GameDev.LanguageType (LANG_TYPE_ID)

